/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TM470Project.ui;

/**
 *
 * @author Joao
 */
public class CalendarPanel extends javax.swing.JPanel {

    /**
     * Creates new form CalendarPanel
     */
    public CalendarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnButton = new javax.swing.JButton();
        prevMonthButton = new javax.swing.JButton();
        monthLabel = new javax.swing.JLabel();
        nextMonthButton = new javax.swing.JButton();
        date1 = new javax.swing.JButton();
        date2 = new javax.swing.JButton();
        date3 = new javax.swing.JButton();
        date4 = new javax.swing.JButton();
        date5 = new javax.swing.JButton();
        date6 = new javax.swing.JButton();
        date11 = new javax.swing.JButton();
        date16 = new javax.swing.JButton();
        date21 = new javax.swing.JButton();
        date26 = new javax.swing.JButton();
        date31 = new javax.swing.JButton();
        date7 = new javax.swing.JButton();
        date8 = new javax.swing.JButton();
        date9 = new javax.swing.JButton();
        date10 = new javax.swing.JButton();
        date12 = new javax.swing.JButton();
        date13 = new javax.swing.JButton();
        date14 = new javax.swing.JButton();
        date15 = new javax.swing.JButton();
        date17 = new javax.swing.JButton();
        date18 = new javax.swing.JButton();
        date19 = new javax.swing.JButton();
        date20 = new javax.swing.JButton();
        date22 = new javax.swing.JButton();
        date23 = new javax.swing.JButton();
        date24 = new javax.swing.JButton();
        date25 = new javax.swing.JButton();
        date27 = new javax.swing.JButton();
        date28 = new javax.swing.JButton();
        date29 = new javax.swing.JButton();
        date30 = new javax.swing.JButton();
        visualizeDataButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        returnButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        returnButton.setText("<");
        returnButton.setToolTipText("Return to the previous screen.");

        prevMonthButton.setText("<");
        prevMonthButton.setToolTipText("Previous month");

        monthLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        monthLabel.setText("<<getMonth>>");

        nextMonthButton.setText(">");
        nextMonthButton.setToolTipText("Next month");

        date1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date1.setText("1");

        date2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date2.setText("2");

        date3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date3.setText("3");

        date4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date4.setText("4");
        date4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date4ActionPerformed(evt);
            }
        });

        date5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date5.setText("5");

        date6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date6.setText("6");

        date11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date11.setText("11");

        date16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date16.setText("16");

        date21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date21.setText("21");

        date26.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date26.setText("26");

        date31.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date31.setText("31");

        date7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date7.setText("7");

        date8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date8.setText("8");

        date9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date9.setText("9");

        date10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date10.setText("10");

        date12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date12.setText("12");

        date13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date13.setText("13");

        date14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date14.setText("14");

        date15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date15.setText("15");

        date17.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date17.setText("17");

        date18.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date18.setText("18");

        date19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date19.setText("19");

        date20.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date20.setText("20");

        date22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date22.setText("22");

        date23.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date23.setText("23");

        date24.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date24.setText("24");
        date24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date24ActionPerformed(evt);
            }
        });

        date25.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date25.setText("25");

        date27.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date27.setText("27");

        date28.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date28.setText("28");

        date29.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date29.setText("29");

        date30.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date30.setText("30");

        visualizeDataButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        visualizeDataButton.setText("<<DataV>>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(returnButton)
                        .addGap(18, 18, 18)
                        .addComponent(prevMonthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextMonthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(date26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(date27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(date28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(date31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(visualizeDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(date29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(date30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prevMonthButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(monthLabel)
                            .addComponent(nextMonthButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addComponent(returnButton, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date1)
                    .addComponent(date2)
                    .addComponent(date3)
                    .addComponent(date4)
                    .addComponent(date5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(date10)
                        .addComponent(date9)
                        .addComponent(date8)
                        .addComponent(date7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date11)
                    .addComponent(date12)
                    .addComponent(date13)
                    .addComponent(date14)
                    .addComponent(date15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date20)
                    .addComponent(date19)
                    .addComponent(date18)
                    .addComponent(date17)
                    .addComponent(date16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date25)
                    .addComponent(date24)
                    .addComponent(date23)
                    .addComponent(date22)
                    .addComponent(date21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date26)
                    .addComponent(date27)
                    .addComponent(date28)
                    .addComponent(date29)
                    .addComponent(date30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date31)
                    .addComponent(visualizeDataButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void date4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date4ActionPerformed

    private void date24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date24ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton date1;
    private javax.swing.JButton date10;
    private javax.swing.JButton date11;
    private javax.swing.JButton date12;
    private javax.swing.JButton date13;
    private javax.swing.JButton date14;
    private javax.swing.JButton date15;
    private javax.swing.JButton date16;
    private javax.swing.JButton date17;
    private javax.swing.JButton date18;
    private javax.swing.JButton date19;
    private javax.swing.JButton date2;
    private javax.swing.JButton date20;
    private javax.swing.JButton date21;
    private javax.swing.JButton date22;
    private javax.swing.JButton date23;
    private javax.swing.JButton date24;
    private javax.swing.JButton date25;
    private javax.swing.JButton date26;
    private javax.swing.JButton date27;
    private javax.swing.JButton date28;
    private javax.swing.JButton date29;
    private javax.swing.JButton date3;
    private javax.swing.JButton date30;
    private javax.swing.JButton date31;
    private javax.swing.JButton date4;
    private javax.swing.JButton date5;
    private javax.swing.JButton date6;
    private javax.swing.JButton date7;
    private javax.swing.JButton date8;
    private javax.swing.JButton date9;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JButton nextMonthButton;
    private javax.swing.JButton prevMonthButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton visualizeDataButton;
    // End of variables declaration//GEN-END:variables
}
