/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TM470Project.ui;

import java.time.LocalDate;

import static TM470Project.ui.MainFrame.getWindow;

/**
 * The calendar class which displays a visual representation grid for any given month
 * @author Joao
 * v4 23/07/2023
 */
public class CalendarPanel extends javax.swing.JPanel {

    private LocalDate date;

    /**
     * Creates new form CalendarPanel
     */
    public CalendarPanel() {
        initComponents();
        date = LocalDate.now();
        updateMonthLabel();
    }

    /**
     * The method called for pressing any given date number
     * @param buttonRef the number associated with a date button (e.g. ref for 'date1' button would be '1')
     */
    public void buttonPress(int buttonRef){
        setDate(buttonRef);
        getWindow().getEntrySelectionPanel().updateListing();
        getWindow().changeScreen("ENTRY SELECTION");
    }

    /**
     * This method is called from within the constructor to updateListing the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnButton = new javax.swing.JButton();
        prevMonthButton = new javax.swing.JButton();
        monthLabel = new javax.swing.JLabel();
        nextMonthButton = new javax.swing.JButton();
        date1 = new javax.swing.JButton();
        date2 = new javax.swing.JButton();
        date3 = new javax.swing.JButton();
        date4 = new javax.swing.JButton();
        date5 = new javax.swing.JButton();
        date6 = new javax.swing.JButton();
        date11 = new javax.swing.JButton();
        date16 = new javax.swing.JButton();
        date21 = new javax.swing.JButton();
        date26 = new javax.swing.JButton();
        date31 = new javax.swing.JButton();
        date7 = new javax.swing.JButton();
        date8 = new javax.swing.JButton();
        date9 = new javax.swing.JButton();
        date10 = new javax.swing.JButton();
        date12 = new javax.swing.JButton();
        date13 = new javax.swing.JButton();
        date14 = new javax.swing.JButton();
        date15 = new javax.swing.JButton();
        date17 = new javax.swing.JButton();
        date18 = new javax.swing.JButton();
        date19 = new javax.swing.JButton();
        date20 = new javax.swing.JButton();
        date22 = new javax.swing.JButton();
        date23 = new javax.swing.JButton();
        date24 = new javax.swing.JButton();
        date25 = new javax.swing.JButton();
        date27 = new javax.swing.JButton();
        date28 = new javax.swing.JButton();
        date29 = new javax.swing.JButton();
        date30 = new javax.swing.JButton();
        visualizeDataButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        returnButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        returnButton.setText("<");
        returnButton.setToolTipText("Return to the previous screen.");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        prevMonthButton.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        prevMonthButton.setText("<");
        prevMonthButton.setToolTipText("Previous month");
        prevMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevMonthButtonActionPerformed(evt);
            }
        });

        monthLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        monthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monthLabel.setText("Month");
        monthLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nextMonthButton.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        nextMonthButton.setText(">");
        nextMonthButton.setToolTipText("Next month");
        nextMonthButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextMonthButton.setRolloverEnabled(false);
        nextMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextMonthButtonActionPerformed(evt);
            }
        });

        date1.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date1.setText("1");
        date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1ActionPerformed(evt);
            }
        });

        date2.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date2.setText("2");
        date2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date2ActionPerformed(evt);
            }
        });

        date3.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date3.setText("3");
        date3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date3ActionPerformed(evt);
            }
        });

        date4.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date4.setText("4");
        date4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date4ActionPerformed(evt);
            }
        });

        date5.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date5.setText("5");
        date5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date5ActionPerformed(evt);
            }
        });

        date6.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date6.setText("6");
        date6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date6ActionPerformed(evt);
            }
        });

        date11.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date11.setText("11");
        date11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date11ActionPerformed(evt);
            }
        });

        date16.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date16.setText("16");
        date16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date16ActionPerformed(evt);
            }
        });

        date21.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date21.setText("21");
        date21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date21ActionPerformed(evt);
            }
        });

        date26.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date26.setText("26");
        date26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date26ActionPerformed(evt);
            }
        });

        date31.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date31.setText("31");
        date31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date31ActionPerformed(evt);
            }
        });

        date7.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date7.setText("7");
        date7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date7ActionPerformed(evt);
            }
        });

        date8.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date8.setText("8");
        date8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date8ActionPerformed(evt);
            }
        });

        date9.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date9.setText("9");
        date9.setMaximumSize(new java.awt.Dimension(16, 16));
        date9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date9ActionPerformed(evt);
            }
        });

        date10.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date10.setText("10");
        date10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date10ActionPerformed(evt);
            }
        });

        date12.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date12.setText("12");
        date12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date12ActionPerformed(evt);
            }
        });

        date13.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date13.setText("13");
        date13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date13ActionPerformed(evt);
            }
        });

        date14.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date14.setText("14");
        date14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date14ActionPerformed(evt);
            }
        });

        date15.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date15.setText("15");
        date15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date15ActionPerformed(evt);
            }
        });

        date17.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date17.setText("17");
        date17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date17ActionPerformed(evt);
            }
        });

        date18.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date18.setText("18");
        date18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date18ActionPerformed(evt);
            }
        });

        date19.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date19.setText("19");
        date19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date19ActionPerformed(evt);
            }
        });

        date20.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date20.setText("20");
        date20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date20ActionPerformed(evt);
            }
        });

        date22.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date22.setText("22");
        date22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date22ActionPerformed(evt);
            }
        });

        date23.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date23.setText("23");
        date23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date23ActionPerformed(evt);
            }
        });

        date24.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date24.setText("24");
        date24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date24ActionPerformed(evt);
            }
        });

        date25.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date25.setText("25");
        date25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date25ActionPerformed(evt);
            }
        });

        date27.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date27.setText("27");
        date27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date27ActionPerformed(evt);
            }
        });

        date28.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date28.setText("28");
        date28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date28ActionPerformed(evt);
            }
        });

        date29.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date29.setText("29");
        date29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date29ActionPerformed(evt);
            }
        });

        date30.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        date30.setText("30");
        date30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date30ActionPerformed(evt);
            }
        });

        visualizeDataButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        visualizeDataButton.setText("Visualize");
        visualizeDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizeDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(returnButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prevMonthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextMonthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(date26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(date27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(date28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(date31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(date29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(date30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(visualizeDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prevMonthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextMonthButton, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(date6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(date9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visualizeDataButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Methods for each button press for variables date1 through date31.
     * Running these methods will bring up the Entry Selection Panel with Entries associated with the specified date
     * @param evt internal ActionEvent listener for the methods, used by generated code
     */
    private void date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1ActionPerformed
        buttonPress(1);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date1ActionPerformed

    private void date2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date2ActionPerformed
        buttonPress(2);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date2ActionPerformed

    private void date3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date3ActionPerformed
        buttonPress(3);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date3ActionPerformed

    private void date4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date4ActionPerformed
        buttonPress(4);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date4ActionPerformed

    private void date5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date5ActionPerformed
        buttonPress(5);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date5ActionPerformed

    private void date6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date6ActionPerformed
        buttonPress(6);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date6ActionPerformed

    private void date7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date7ActionPerformed
        buttonPress(7);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date7ActionPerformed

    private void date8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date8ActionPerformed
        buttonPress(8);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date8ActionPerformed

    private void date9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date9ActionPerformed
        buttonPress(9);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date9ActionPerformed

    private void date10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date10ActionPerformed
        buttonPress(10);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date10ActionPerformed

    private void date11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date11ActionPerformed
        buttonPress(11);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date11ActionPerformed

    private void date12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date12ActionPerformed
        buttonPress(12);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date12ActionPerformed

    private void date13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date13ActionPerformed
        buttonPress(13);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date13ActionPerformed

    private void date14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date14ActionPerformed
        buttonPress(14);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date14ActionPerformed

    private void date15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date15ActionPerformed
        buttonPress(15);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date15ActionPerformed

    private void date16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date16ActionPerformed
        buttonPress(16);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date16ActionPerformed

    private void date17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date17ActionPerformed
        buttonPress(17);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date17ActionPerformed

    private void date18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date18ActionPerformed
        buttonPress(18);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date18ActionPerformed

    private void date19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date19ActionPerformed
        buttonPress(19);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date19ActionPerformed

    private void date20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date20ActionPerformed
        buttonPress(20);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date20ActionPerformed

    private void date21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date21ActionPerformed
        buttonPress(21);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date21ActionPerformed

    private void date22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date22ActionPerformed
        buttonPress(22);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date22ActionPerformed

    private void date23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date23ActionPerformed
        buttonPress(23);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date23ActionPerformed

    private void date24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date24ActionPerformed
        buttonPress(24);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date24ActionPerformed

    private void date25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date25ActionPerformed
        buttonPress(25);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date25ActionPerformed

    private void date26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date26ActionPerformed
        buttonPress(26);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date26ActionPerformed

    private void date27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date27ActionPerformed
        buttonPress(27);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date27ActionPerformed

    private void date28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date28ActionPerformed
        buttonPress(28);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date28ActionPerformed

    private void date29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date29ActionPerformed
        buttonPress(29);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date29ActionPerformed

    private void date30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date30ActionPerformed
        buttonPress(30);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date30ActionPerformed

    private void date31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date31ActionPerformed
        buttonPress(31);
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_date31ActionPerformed

    /**
     * Method for button used in changing screens to the Data View Panel
     * @param evt internal ActionEvent listener for the methods, used by generated code
     */
    private void visualizeDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizeDataButtonActionPerformed
        getWindow().getDataViewPanel().initialize();
        getWindow().getDataViewPanel().updateMonth();
        getWindow().changeScreen("VIEW DATA");
    }//GEN-LAST:event_visualizeDataButtonActionPerformed

    /**
     * Method for button used in changing screens for returning to the previous panel
     * @param evt internal ActionEvent listener for the methods, used by generated code
     */
    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        getWindow().changeScreen("MAIN");
        //reset date to system date
        date = LocalDate.now();
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * Changes month value of date to be one month previous
     * @param evt internal ActionEvent listener for the methods, used by generated code
     */
    private void prevMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevMonthButtonActionPerformed
        date = date.minusMonths(1);
        updateMonthLabel();
    }//GEN-LAST:event_prevMonthButtonActionPerformed

    /**
     * Changes month value of date to be one month forward
     * @param evt internal ActionEvent listener for the methods, used by generated code
     */
    private void nextMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextMonthButtonActionPerformed
        date = date.plusMonths(1);
        updateMonthLabel();
    }//GEN-LAST:event_nextMonthButtonActionPerformed

    /**
     * Getter for date variable
     * @return the currently selected date
     */
    public LocalDate getDate(){ return date;}

    /**
     * @param aDate the full date in format YYYY-MM-DD
     */
    public void setDate(LocalDate aDate){
        date = aDate;
        System.out.println("Selected date = " + date);
        getWindow().getEntrySelectionPanel().updateTitle();
    }

    /**
     * @param day an int input for the selected day when pressing a button
     */
    public void setDate(int day){
        date = LocalDate.of(date.getYear(), date.getMonth(), day);
        System.out.println("Selected date = " + date);
        getWindow().getEntrySelectionPanel().updateTitle();
    }

    /**
     * Updates month label with current date and hides buttons for non-existing days (e.g. February 31st)
     */
    public void updateMonthLabel(){
        //set label text to month value in abbreviated format
        monthLabel.setText(date.getMonth().toString().substring(0,3) + " " + date.getYear());

        //sets button visibilities for days 29 to 31
        if(date.lengthOfMonth() < 29){
            date29.setVisible(false);
        }
        else{
            date29.setVisible(true);
        }

        if(date.lengthOfMonth() < 30){
            date30.setVisible(false);
        }
        else{
            date30.setVisible(true);
        }

        if(date.lengthOfMonth() < 31){
            date31.setVisible(false);
        }
        else{
            date31.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton date1;
    private javax.swing.JButton date10;
    private javax.swing.JButton date11;
    private javax.swing.JButton date12;
    private javax.swing.JButton date13;
    private javax.swing.JButton date14;
    private javax.swing.JButton date15;
    private javax.swing.JButton date16;
    private javax.swing.JButton date17;
    private javax.swing.JButton date18;
    private javax.swing.JButton date19;
    private javax.swing.JButton date2;
    private javax.swing.JButton date20;
    private javax.swing.JButton date21;
    private javax.swing.JButton date22;
    private javax.swing.JButton date23;
    private javax.swing.JButton date24;
    private javax.swing.JButton date25;
    private javax.swing.JButton date26;
    private javax.swing.JButton date27;
    private javax.swing.JButton date28;
    private javax.swing.JButton date29;
    private javax.swing.JButton date3;
    private javax.swing.JButton date30;
    private javax.swing.JButton date31;
    private javax.swing.JButton date4;
    private javax.swing.JButton date5;
    private javax.swing.JButton date6;
    private javax.swing.JButton date7;
    private javax.swing.JButton date8;
    private javax.swing.JButton date9;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JButton nextMonthButton;
    private javax.swing.JButton prevMonthButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton visualizeDataButton;
    // End of variables declaration//GEN-END:variables
}
