/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TM470Project.ui;

/**
 *
 * @author Joao
 */
public class CalendarPanel extends javax.swing.JPanel {

    /**
     * Creates new form CalendarPanel
     */
    public CalendarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnButton = new javax.swing.JButton();
        prevMonthButton = new javax.swing.JButton();
        monthLabel = new javax.swing.JLabel();
        nextMonthButton = new javax.swing.JButton();
        date1 = new javax.swing.JButton();
        date2 = new javax.swing.JButton();
        date3 = new javax.swing.JButton();
        date4 = new javax.swing.JButton();
        date5 = new javax.swing.JButton();
        date6 = new javax.swing.JButton();
        date11 = new javax.swing.JButton();
        date16 = new javax.swing.JButton();
        date21 = new javax.swing.JButton();
        date26 = new javax.swing.JButton();
        date31 = new javax.swing.JButton();
        date7 = new javax.swing.JButton();
        date8 = new javax.swing.JButton();
        date9 = new javax.swing.JButton();
        date10 = new javax.swing.JButton();
        date12 = new javax.swing.JButton();
        date13 = new javax.swing.JButton();
        date14 = new javax.swing.JButton();
        date15 = new javax.swing.JButton();
        date17 = new javax.swing.JButton();
        date18 = new javax.swing.JButton();
        date19 = new javax.swing.JButton();
        date20 = new javax.swing.JButton();
        date22 = new javax.swing.JButton();
        date23 = new javax.swing.JButton();
        date24 = new javax.swing.JButton();
        date25 = new javax.swing.JButton();
        date27 = new javax.swing.JButton();
        date28 = new javax.swing.JButton();
        date29 = new javax.swing.JButton();
        date30 = new javax.swing.JButton();
        visualizeDataButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        returnButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        returnButton.setText("<");
        returnButton.setToolTipText("Return to the previous screen.");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        prevMonthButton.setText("<");
        prevMonthButton.setToolTipText("Previous month");
        prevMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevMonthButtonActionPerformed(evt);
            }
        });

        monthLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        monthLabel.setText("<<getMonth>>");

        nextMonthButton.setText(">");
        nextMonthButton.setToolTipText("Next month");
        nextMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextMonthButtonActionPerformed(evt);
            }
        });

        date1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date1.setText("1");
        date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1ActionPerformed(evt);
            }
        });

        date2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date2.setText("2");
        date2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date2ActionPerformed(evt);
            }
        });

        date3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date3.setText("3");
        date3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date3ActionPerformed(evt);
            }
        });

        date4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date4.setText("4");
        date4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date4ActionPerformed(evt);
            }
        });

        date5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date5.setText("5");
        date5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date5ActionPerformed(evt);
            }
        });

        date6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date6.setText("6");
        date6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date6ActionPerformed(evt);
            }
        });

        date11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date11.setText("11");
        date11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date11ActionPerformed(evt);
            }
        });

        date16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date16.setText("16");
        date16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date16ActionPerformed(evt);
            }
        });

        date21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date21.setText("21");
        date21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date21ActionPerformed(evt);
            }
        });

        date26.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date26.setText("26");
        date26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date26ActionPerformed(evt);
            }
        });

        date31.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date31.setText("31");
        date31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date31ActionPerformed(evt);
            }
        });

        date7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date7.setText("7");
        date7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date7ActionPerformed(evt);
            }
        });

        date8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date8.setText("8");
        date8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date8ActionPerformed(evt);
            }
        });

        date9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date9.setText("9");
        date9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date9ActionPerformed(evt);
            }
        });

        date10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date10.setText("10");
        date10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date10ActionPerformed(evt);
            }
        });

        date12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date12.setText("12");
        date12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date12ActionPerformed(evt);
            }
        });

        date13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date13.setText("13");
        date13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date13ActionPerformed(evt);
            }
        });

        date14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date14.setText("14");
        date14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date14ActionPerformed(evt);
            }
        });

        date15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date15.setText("15");
        date15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date15ActionPerformed(evt);
            }
        });

        date17.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date17.setText("17");
        date17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date17ActionPerformed(evt);
            }
        });

        date18.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date18.setText("18");
        date18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date18ActionPerformed(evt);
            }
        });

        date19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date19.setText("19");
        date19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date19ActionPerformed(evt);
            }
        });

        date20.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date20.setText("20");
        date20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date20ActionPerformed(evt);
            }
        });

        date22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date22.setText("22");
        date22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date22ActionPerformed(evt);
            }
        });

        date23.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date23.setText("23");
        date23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date23ActionPerformed(evt);
            }
        });

        date24.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date24.setText("24");
        date24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date24ActionPerformed(evt);
            }
        });

        date25.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date25.setText("25");
        date25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date25ActionPerformed(evt);
            }
        });

        date27.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date27.setText("27");
        date27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date27ActionPerformed(evt);
            }
        });

        date28.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date28.setText("28");
        date28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date28ActionPerformed(evt);
            }
        });

        date29.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date29.setText("29");
        date29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date29ActionPerformed(evt);
            }
        });

        date30.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date30.setText("30");
        date30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date30ActionPerformed(evt);
            }
        });

        visualizeDataButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        visualizeDataButton.setText("<<DataV>>");
        visualizeDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizeDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(returnButton)
                        .addGap(18, 18, 18)
                        .addComponent(prevMonthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextMonthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(date26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(date27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(date28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(date31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(visualizeDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(date29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(date30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prevMonthButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(monthLabel)
                            .addComponent(nextMonthButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addComponent(returnButton, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date1)
                    .addComponent(date2)
                    .addComponent(date3)
                    .addComponent(date4)
                    .addComponent(date5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(date10)
                        .addComponent(date9)
                        .addComponent(date8)
                        .addComponent(date7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date11)
                    .addComponent(date12)
                    .addComponent(date13)
                    .addComponent(date14)
                    .addComponent(date15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date20)
                    .addComponent(date19)
                    .addComponent(date18)
                    .addComponent(date17)
                    .addComponent(date16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date25)
                    .addComponent(date24)
                    .addComponent(date23)
                    .addComponent(date22)
                    .addComponent(date21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date26)
                    .addComponent(date27)
                    .addComponent(date28)
                    .addComponent(date29)
                    .addComponent(date30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visualizeDataButton)
                    .addComponent(date31))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void date4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date4ActionPerformed

    private void date24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date24ActionPerformed

    private void date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date1ActionPerformed

    private void date2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date2ActionPerformed

    private void date3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date3ActionPerformed

    private void date5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date5ActionPerformed

    private void date6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date6ActionPerformed

    private void date7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date7ActionPerformed

    private void date8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date8ActionPerformed

    private void date9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date9ActionPerformed

    private void date10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date10ActionPerformed

    private void date11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date11ActionPerformed

    private void date12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date12ActionPerformed

    private void date13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date13ActionPerformed

    private void date14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date14ActionPerformed

    private void date15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date15ActionPerformed

    private void date16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date16ActionPerformed

    private void date17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date17ActionPerformed

    private void date18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date18ActionPerformed

    private void date19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date19ActionPerformed

    private void date20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date20ActionPerformed

    private void date21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date21ActionPerformed

    private void date22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date22ActionPerformed

    private void date23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date23ActionPerformed

    private void date25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date25ActionPerformed

    private void date26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date26ActionPerformed

    private void date27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date27ActionPerformed

    private void date28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date28ActionPerformed

    private void date29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date29ActionPerformed

    private void date30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date30ActionPerformed

    private void date31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date31ActionPerformed

    private void visualizeDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizeDataButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visualizeDataButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnButtonActionPerformed

    private void prevMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevMonthButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prevMonthButtonActionPerformed

    private void nextMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextMonthButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextMonthButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton date1;
    private javax.swing.JButton date10;
    private javax.swing.JButton date11;
    private javax.swing.JButton date12;
    private javax.swing.JButton date13;
    private javax.swing.JButton date14;
    private javax.swing.JButton date15;
    private javax.swing.JButton date16;
    private javax.swing.JButton date17;
    private javax.swing.JButton date18;
    private javax.swing.JButton date19;
    private javax.swing.JButton date2;
    private javax.swing.JButton date20;
    private javax.swing.JButton date21;
    private javax.swing.JButton date22;
    private javax.swing.JButton date23;
    private javax.swing.JButton date24;
    private javax.swing.JButton date25;
    private javax.swing.JButton date26;
    private javax.swing.JButton date27;
    private javax.swing.JButton date28;
    private javax.swing.JButton date29;
    private javax.swing.JButton date3;
    private javax.swing.JButton date30;
    private javax.swing.JButton date31;
    private javax.swing.JButton date4;
    private javax.swing.JButton date5;
    private javax.swing.JButton date6;
    private javax.swing.JButton date7;
    private javax.swing.JButton date8;
    private javax.swing.JButton date9;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JButton nextMonthButton;
    private javax.swing.JButton prevMonthButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton visualizeDataButton;
    // End of variables declaration//GEN-END:variables
}
