/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TM470Project.ui;

import TM470Project.Entry;
import TM470Project.EntryType;
import TM470Project.TM470ProjectRunner;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import static TM470Project.ui.MainFrame.getWindow;

/**
 * Class representing the window panel for creating a new Entry
 * @author Joao
 * v4 23/07/2023
 */
public class CreateEntryPanel extends javax.swing.JPanel {
    private static Optional<List> typesList;

    /**
     * Creates new form CreateEntryPanel
     */
    public CreateEntryPanel() {
        initComponents();
        populateTypeComboBox();

        yearComboBox.removeAllItems();

        /* populates a list with 100 years from current year in regressive order */
        int year = LocalDate.now().getYear();
        for(int i = 0; i < 100; i++){
            yearComboBox.addItem(String.valueOf(year));
            year -= 1;
        }
    }

    /**
     * This method populates drop down menu list with queried EntryType items
     */
    public void populateTypeComboBox() {
        /* removes all items from combo box before adding current ones */
        typeComboBox.removeAllItems();

        /* populates list with entry types */
        typesList = Optional.ofNullable(TM470ProjectRunner.getController().findAllEntryTypes());
        EntryType entryType;
        if(typesList.isPresent()){
            for (int i = 0; i < typesList.get().size(); i++){
                entryType = (EntryType) typesList.get().get(i);
                typeComboBox.addItem(entryType.getName());
            }
        }
    }

    /**
     * This method is called from within the constructor to updateListing the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        inputLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        inputField = new javax.swing.JTextField();
        typeComboBox = new javax.swing.JComboBox<>();
        dayComboBox = new javax.swing.JComboBox<>();
        monthComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        toTypeSelectionButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(246, 230));

        returnButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        returnButton.setText("<");
        returnButton.setToolTipText("Return to the previous screen.");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleLabel.setText("Create Entry");

        typeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        typeLabel.setText("Type");

        inputLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputLabel.setText("Input");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dateLabel.setText("Date");

        confirmButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.setToolTipText("Finalize your entry.");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        inputField.setToolTipText("The numerical input for the entry.");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<getEntryTypeList>>" }));
        typeComboBox.setToolTipText("The entry type for your entry.");

        dayComboBox.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        dayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayComboBox.setSelectedIndex(LocalDate.now().getDayOfMonth()-1);

        monthComboBox.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        monthComboBox.setSelectedIndex(LocalDate.now().getMonthValue()-1);

        yearComboBox.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "<<fill this out using some code>>" }));
        yearComboBox.setName(""); // NOI18N

        toTypeSelectionButton.setText("...");
        toTypeSelectionButton.setToolTipText("Create entry type.");
        toTypeSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTypeSelectionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(returnButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confirmButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel)
                            .addComponent(inputLabel)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dayComboBox, 0, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inputField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(typeComboBox, 0, 158, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toTypeSelectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnButton)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toTypeSelectionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dayComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(confirmButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Changes screen to Main Panel
     * @param evt internal ActionEvent listener for the methods, used by generated code
     */
    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        getWindow().changeScreen("MAIN");
        populateTypeComboBox();
        getWindow().getEditEntryPanel().populateTypeComboBox();
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * Changes screen to Entry Type Selection Panel
     * @param evt internal ActionEvent listener for the methods, used by generated code
     */
    private void toTypeSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTypeSelectionButtonActionPerformed
        getWindow().setPreviousScreenRef("CREATE ENTRY");
        getWindow().changeScreen("TYPE SELECTION");
    }//GEN-LAST:event_toTypeSelectionButtonActionPerformed

    /**
     * Method for saving Entry and returning to Main Panel
     * @param evt internal ActionEvent listener for the methods, used by generated code
     */
    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        System.out.println("Confirm button pressed");
        String typeInput = typeComboBox.getItemAt(typeComboBox.getSelectedIndex());
        String dateDayInput = dayComboBox.getItemAt(dayComboBox.getSelectedIndex());
        String dateMonthInput = monthComboBox.getItemAt(monthComboBox.getSelectedIndex());
        String dateYearInput = yearComboBox.getItemAt(yearComboBox.getSelectedIndex());
        String metricInput = inputField.getText();

        System.out.println("typeInput: " + typeInput);
        System.out.println("dateInput: " + dateDayInput + "/" + dateMonthInput + "/" + dateYearInput);
        System.out.println("kcalInput: " + metricInput);

        LocalDate date = LocalDate.now();
        //try to set date input as a LocalDate value
        try{
            date = LocalDate.of(Integer.parseInt(dateYearInput), Integer.parseInt(dateMonthInput), Integer.parseInt(dateDayInput));
        }
        catch(Exception e){
            System.out.println("Date input is invalid");
            return;
        }

        EntryType entryType;
        //try set entry type input as existing Entry Type object
        try{
            entryType = TM470ProjectRunner.getController().findEntryTypeByName(typeInput);
        }
        catch(Exception e){
            System.out.println("Entry Type input is invalid");
            return;
        }

        int metricValue = 0;
        //try to convert metric input string value to int
        try {
            metricValue = Integer.parseInt(metricInput);
        }
        catch(NumberFormatException nfe){
            System.out.println();
        }

        //creates entry if all try/catch blocks pass
        Entry entry = new Entry(entryType, metricValue, date);
        TM470ProjectRunner.getController().saveEntry(entry);

        getWindow().changeScreen("MAIN");
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * Getter for typeList variable
     * @return an Optional containing a List of EntryTypes if any exist
     */
    public static Optional<List> getTypesList(){
        return typesList;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox<String> dayComboBox;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton toTypeSelectionButton;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
