/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TM470Project.ui;

import TM470Project.Entry;
import TM470Project.EntryType;

import java.time.LocalDate;

import static TM470Project.ui.MainFrame.getWindow;

/**
 * Class representing the window panel for editing an existing Entry
 * @author Joao
 * v4 23/07/2023
 */
public class EditEntryPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditEntryPanel
     */
    public EditEntryPanel() {
        initComponents();
        populateTypeComboBox();

        yearComboBox.removeAllItems();

        /* populates a list with 100 years from current year in regressive order */
        int year = LocalDate.now().getYear();
        for(int i = 0; i < 100; i++){
            yearComboBox.addItem(String.valueOf(year));
            year -= 1;
        }
    }

    /**
     * This method is called from within the constructor to updateListing the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();
        inputLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        inputField = new javax.swing.JTextField();
        typeComboBox = new javax.swing.JComboBox<>();
        dayComboBox = new javax.swing.JComboBox<>();
        monthComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        titleLabel = new javax.swing.JLabel();
        toTypeSelectionButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        returnButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        returnButton.setText("<");
        returnButton.setToolTipText("Return to the previous screen.");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setToolTipText("Delete the entry.");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        typeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        typeLabel.setText("Type");

        inputLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputLabel.setText("Input");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dateLabel.setText("Date");

        confirmButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.setToolTipText("Finalize your entry.");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        inputField.setToolTipText("The numerical input for the entry.");

        typeComboBox.setEditable(true);
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(keep for now)" }));
        typeComboBox.setToolTipText("The entry type for your entry.");

        dayComboBox.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        dayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        monthComboBox.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        yearComboBox.setEditable(true);
        yearComboBox.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "<<fill this out using some code>>" }));
        yearComboBox.setName(""); // NOI18N

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleLabel.setText("Edit Entry");

        toTypeSelectionButton.setText("...");
        toTypeSelectionButton.setToolTipText("Create entry type.");
        toTypeSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTypeSelectionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(returnButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confirmButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel)
                            .addComponent(inputLabel)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dayComboBox, 0, 56, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inputField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(typeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toTypeSelectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(returnButton)
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toTypeSelectionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dayComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(confirmButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method to update the fields' default values to those of the selected Entry
     */
    public void updateFields(){
        //TODO update fields with selected type from EntrySelectionPanel
        Entry mockEntry = getWindow().getEntrySelectionPanel().getSelectedEntry();

        inputField.setText(String.valueOf(mockEntry.getMetric()));
        typeComboBox.setSelectedItem(mockEntry.getType().getName()); //TODO leave for now, probably remove though
        dayComboBox.setSelectedItem(String.valueOf(mockEntry.getDate().getDayOfMonth()));
        monthComboBox.setSelectedItem(String.valueOf(mockEntry.getDate().getMonthValue()));
        yearComboBox.setSelectedItem(String.valueOf(mockEntry.getDate().getYear()));
    }

    /**
     * This method populates drop down menu list with queried EntryType items
     */
    public void populateTypeComboBox() {
        /* removes all items from combo box before adding current ones */
        typeComboBox.removeAllItems();

        /* populates list with entry types */
        EntryType entryType;
        if(CreateEntryPanel.getTypesList().isPresent()){
            for (int i = 0; i < CreateEntryPanel.getTypesList().get().size(); i++){
                entryType = (EntryType) CreateEntryPanel.getTypesList().get().get(i);
                typeComboBox.addItem(entryType.getName());
            }
        }
    }
    /**
     * Method for deleting the selected Entry
     * @param evt internal ActionEvent listener for the methods, used by generated code
     */
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO confirm if they want to delete, if so delete


        getWindow().getEntrySelectionPanel().updateListing();
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * Method for returning to the EntrySelectionPanel
     * @param evt internal ActionEvent listener for the methods, used by generated code
     */
    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * Method to change screen to the TypeSelectionPanel, while keeping a reference of screen pathing
     * @param evt internal ActionEvent listener for the methods, used by generated code
     */
    private void toTypeSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTypeSelectionButtonActionPerformed
        getWindow().setPreviousScreenRef("EDIT ENTRY");
        getWindow().changeScreen("TYPE SELECTION");
    }//GEN-LAST:event_toTypeSelectionButtonActionPerformed

    /**
     * Method for saving changes to the selected Entry
     * @param evt internal ActionEvent listener for the methods, used by generated code
     */
    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO make changes to entry

        getWindow().getEntrySelectionPanel().updateListing();
        getWindow().changeScreen("ENTRY SELECTION");
    }//GEN-LAST:event_confirmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox<String> dayComboBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton toTypeSelectionButton;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
