/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TM470Project.ui;

/**
 *
 * @author Joao
 */
public class EntrySelectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form EntrySelectionPanel
     */
    public EntrySelectionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnButton = new javax.swing.JButton();
        scrollBar = new javax.swing.JScrollBar();
        entry1 = new javax.swing.JButton();
        entry2 = new javax.swing.JButton();
        entry3 = new javax.swing.JButton();
        entry6 = new javax.swing.JButton();
        entry5 = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        entry4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        returnButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        returnButton.setText("<");
        returnButton.setToolTipText("Return to the previous screen.");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        entry1.setText("<<anEntry>>");
        entry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entry1ActionPerformed(evt);
            }
        });

        entry2.setText("<<anEntry>>");
        entry2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entry2ActionPerformed(evt);
            }
        });

        entry3.setText("<<anEntry>>");
        entry3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entry3ActionPerformed(evt);
            }
        });

        entry6.setText("<<anEntry>>");
        entry6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entry6ActionPerformed(evt);
            }
        });

        entry5.setText("<<anEntry>>");
        entry5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entry5ActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleLabel.setText("<<getDate>>");
        titleLabel.setToolTipText("");

        entry4.setText("<<anEntry>>");
        entry4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entry4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(returnButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(entry1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(entry2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(entry3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(entry6, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(entry5, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(entry4, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnButton)
                            .addComponent(titleLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entry1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entry2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entry3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entry4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entry5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entry6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollBar, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entry1ActionPerformed

    private void entry2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entry2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entry2ActionPerformed

    private void entry3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entry3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entry3ActionPerformed

    private void entry6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entry6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entry6ActionPerformed

    private void entry5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entry5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entry5ActionPerformed

    private void entry4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entry4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entry4ActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entry1;
    private javax.swing.JButton entry2;
    private javax.swing.JButton entry3;
    private javax.swing.JButton entry4;
    private javax.swing.JButton entry5;
    private javax.swing.JButton entry6;
    private javax.swing.JButton returnButton;
    private javax.swing.JScrollBar scrollBar;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
